// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: HasMaps.shared.kt
// Package: com.lightningkite.butterfly.maps

//! Declares com.lightningkite.butterfly.maps.hasMaps
export function hasMaps(): boolean { return true; }
